### ISSUE TITLE
role failes on "Register agent service status" step

### ISSUE THREAD

**Issue by yagilm** [gsoft-inc/ansible-role-azure-devops-agent#15]
Hello, 
the step `Register agent service status` does not work. This is because it uses ./svc.sh that does not exist. It is created only after running the `Configure agent as build server` or `Configure agent as deployment server.`
svc.sh exists in bin/runsvc.sh but it doesn't produce the required text ("not installed").
I am running this on a Ubuntu 18.04.4 LTS VM.

I am currently working on a solution, I could make a pull request when I'm done.

**Comment by yohanb** [comment]
@yagilm thanks, I'll have a look on my side as well.

**Comment by yagilm** [comment]
@yohanb I have a fix that is tested and works. If you want give me access and I will push the branch and do a pull request.
The differences are:
- agent status registration status cmd (1 line)
- build agent command arguments (2 lines)
- install dependencies via shipped script (./bin/installdependencies.sh), (1 task, 5 lines)

**Comment by yohanb** [comment]
@yagilm done!  Waiting for you PR.

**Comment by yohanb** [comment]
@yagilm can't you create a PR from a fork?  I don't really want to micro manage permissions. 
Thanks 👍

**Comment by yagilm** [comment]
yes, that's cleaner.
PR16 done
