### ISSUE TITLE
gsoft.azure_devops_agent was not found

### ISSUE THREAD

**Issue by bruun365** [gsoft-inc/ansible-role-azure-devops-agent#17]
Tried to install the software, but got the following error: 
**[WARNING]: - gsoft.azure_devops_agent was NOT installed successfully: - sorry, gsoft.azure_devops_agent was not found
on https://galaxy.ansible.com/api/**

**Comment by stamenic** [comment]
Same here, it's not finding it on galaxy.

**Comment by yohanb** [comment]
Hey guys, the error should be resolved.  Keep me posted.
In any case, if it still doesn't work, try `yohanb.azure_devops_agent`

**Comment by TJEvans** [comment]
Wasent working for me today, so made use of yohanb.*

**Comment by bruun365** [comment]
Also wasn't working for  me, so made use of yohanb.*

**Comment by yohanb** [comment]
![image](https://user-images.githubusercontent.com/812993/81861400-2fbe6180-9536-11ea-8786-fbc8fa682656.png)
works!
