### ISSUE TITLE
Agent is reinstalled every time the playbook is run

### ISSUE THREAD

**Issue by krknopp** [gsoft-inc/ansible-role-azure-devops-agent#9]
Unless I'm missing something, every time this is run, the Agent is reinstalled.  Is that expected?  I had to write some logic in to prevent this from happening.

**Comment by marchenm** [comment]
one possible solution is adding a `reconfigure` variable and adding it to the when statements for the uninstall and unconfigure tasks, and using the `when: service_running.rc == 1 or reconfigure` statement to configure and install the agent. This way the role will be idempotent. 

Additionally, you can write the variables to file and only reinstall when that file changes.

**Comment by yohanb** [comment]
indeed, that could be a better way to be idempotent.  I'll have time to test it out next week.  If ever you want to submit a pr for the change, that would also be great.
✌️

**Comment by krknopp** [comment]
@yohanb did you ever make any progress on this?  I was going to try to work on it, as I really need it, but didn't want to duplicate any of your work.

**Comment by yohanb** [comment]
@krknopp no it fell off my radar 😕
I can have a look at it tomorrow!

**Comment by krknopp** [comment]
That'd be awesome.  I have a feeling you'll be faster than I would be, but let me know if you don't think you'll have time.
